import '@react-navigation/native';

declare module '@react-navigation/native' {
  export type ExtendedTheme = {
    dark: boolean;
    colors: {
      primary: string;
      primaryDark: string;
      primaryDarker: string;
      primaryDarkest: string;
      primaryLight: string;
      primaryLighter: string;
      primaryLightest: string;
      secondary: string;
      secondaryDark: string;
      secondaryDarker: string;
      secondaryDarkest: string;
      secondaryLight: string;
      secondaryLighter: string;
      secondaryLightest: string;
      success: string;
      successDark: string;
      successDarker: string;
      successDarkest: string;
      successLight: string;
      successLighter: string;
      successLightest: string;
      info: string;
      infoDark: string;
      infoDarker: string;
      infoDarkest: string;
      infoLight: string;
      infoLighter: string;
      infoLightest: string;
      warning: string;
      warningDark: string;
      warningDarker: string;
      warningDarkest: string;
      warningLight: string;
      warningLighter: string;
      warningLightest: string;
      danger: string;
      dangerDark: string;
      dangerDarker: string;
      dangerDarkest: string;
      dangerLight: string;
      dangerLighter: string;
      dangerLightest: string;
      background: string;
      card: string;
      text: string;
      textSecondary: string;
      border: string;
      notification: string;
      white: string;
      black: string;
      background_000: string;
      background_050: string;
      background_100: string;
      background_200: string;
      background_300: string;
      background_400: string;
      background_500: string;
      background_600: string;
      background_700: string;
      background_800: string;
      background_900: string;
      background_1000: string;
    };
  };
  export function useTheme(): ExtendedTheme;
}
